name = "UncValue"
uuid = "a746a8ee-edd7-11ea-299b-9348cedadb4f"
license = "Apache"
authors = ["Adria Labay <adria.labay@gmail.com>", "Àlex Giménez Romero <gimenez.romero.alex@gmail.com>"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"

[extras]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Statistics"]
